name: precompile-freebsd

on:
  push:
    tags:
      - "v*"
      - "freebsd-*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  freebsd:
    runs-on: ubuntu-latest
    env:
      OTP_VERSION: "25.3.2.14"
      NIF_VERSION: "2.16"
      ELIXIR_VERSION: "1.17.3"
    strategy:
      matrix:
        job:
          - { fullversion: "13.5", major: "13" }
      fail-fast: false

    name: x86_64-unknown-freebsd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Precompiled OTP
        id: cache-otp
        uses: actions/cache@v4
        with:
          key: precompile-otp-${{ env.OTP_VERSION }}-x86_64-unknown-freebsd${{ matrix.job.major }}
          path: |
            ./otp-x86_64-unknown-freebsd${{ matrix.job.major }}.tar.gz

      - name: Download Precompiled OTP
        if: steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          curl -fSL "https://github.com/cocoa-xu/otp-build/releases/download/v${{ env.OTP_VERSION }}/otp-x86_64-unknown-freebsd${{ matrix.job.major }}.tar.gz" -o "otp-x86_64-unknown-freebsd${{ matrix.job.major }}.tar.gz"

      - name: Compile in FreeBSD
        id: compile-freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          envs: "OTP_VERSION ELIXIR_VERSION NIF_VERSION"
          release: ${{ matrix.job.fullversion }}
          usesh: true
          prepare: |
            pkg install -y gmake cmake llvm python3 git curl openssl ca_root_nss pkgconf ncurses unzip sudo ccache openblas

          run: |
            export TRIPLET="x86_64-unknown-freebsd"
            export ROOT_DIR="$(pwd)"
            export EVISION_PREFER_PRECOMPILED="false"
            export OTP_MAIN_VER="${OTP_VERSION%%.*}"
            export MIX_ENV="prod"

            export TAGGED_VERSION="${GITHUB_REF##*/v}"
            if [ "${GITHUB_REF}" = "${TAGGED_VERSION}" ]; then
              export TAGGED_VERSION="freebsd"
            fi

            sudo tar -xzf "otp-x86_64-unknown-freebsd${{ matrix.job.major }}.tar.gz" -C /

            mkdir -p "${ROOT_DIR}/elixir-${ELIXIR_VERSION}"
            cd "${ROOT_DIR}/elixir-${ELIXIR_VERSION}"
            curl -fSL "https://github.com/elixir-lang/elixir/releases/download/v${ELIXIR_VERSION}/elixir-otp-${OTP_MAIN_VER}.zip" -o "elixir-otp-${OTP_MAIN_VER}.zip"
            unzip -q "elixir-otp-${OTP_MAIN_VER}.zip"
            export PATH="$(pwd)/bin:${PATH}"
            cd "${ROOT_DIR}"

            mix local.hex --force
            mix local.rebar --force

            mix deps.get
            export EVISION_ENABLE_CONTRIB=false
            rm -rf lib/generated && rm -rf src/generated
            PKG_NAME='evision-nif_'"${NIF_VERSION}"'-'"${TRIPLET}"'-'"${TAGGED_VERSION}"
            mkdir -p ${PKG_NAME}
            mkdir -p ./_build/prod/lib/evision/priv/include
            touch ./_build/prod/lib/evision/priv/a.so
            mkdir -p lib/generated && mkdir -p src/generated
            echo "PRIV_DIR: ${ROOT_DIR}/_build/prod/lib/evision/priv"
            PRIV_DIR="./_build/prod/lib/evision/priv"
            echo "PRIV_DIR: ./_build/prod/lib/evision/priv"
            echo "mv"
            mv "./_build/prod/lib/evision/priv/include" /tmp/include
            echo "cp -a"
            cp -a ./_build/prod/lib/evision/priv "${PKG_NAME}"
            echo "cp -a lib/generated ${PKG_NAME}/elixir_generated"
            cp -a lib/generated "${PKG_NAME}/elixir_generated"
            echo "cp -a src/generated ${PKG_NAME}/erlang_generated"
            cp -a src/generated "${PKG_NAME}/erlang_generated"
            echo "tar -czf ${PKG_NAME}.tar.gz ${PKG_NAME}"
            tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
            echo "rm -rf ${PKG_NAME}"
            rm -rf "${PKG_NAME}"
            echo "ls -lah ${PKG_NAME}.tar.gz"
            ls -lah "${PKG_NAME}.tar.gz"
            echo "mkdir -p artifacts"
            mkdir -p artifacts
            echo "mv ${PKG_NAME}.tar.gz artifacts"
            mv "${PKG_NAME}.tar.gz" artifacts
            echo "cd artifacts"
            cd artifacts
            echo "sha256sum"
            sha256sum "${PKG_NAME}.tar.gz" | tee "${PKG_NAME}.tar.gz.sha256"
            mv "${PKG_NAME}.tar.gz.sha256" ${ROOT_DIR}
            mv "${PKG_NAME}.tar.gz" ${ROOT_DIR}
            cd ${ROOT_DIR}
            echo "ls -lah"
            sleep 5

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/freebsd-')
        with:
          files: |
            evision-nif_*.tar.gz
            evision-nif_*.sha256
