name: linux-precompile-aarch64-cuda-gnu

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aarch64-linux-gnu-cuda:
    runs-on: ${{ matrix.pair.runner }}
    env:
      OTP_VERSION: "25.3.2.12"
      ELIXIR_VERSION: "1.16.1"
      TRIPLET: "aarch64-linux-gnu"
      CMAKE_CUDA_ARCHITECTURES: "50,52,60,61,70,72,75,80,86,89,90,100,120"
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch: aarch64-linux-gnu
              runner: ubicloud-standard-4-arm
              cuda_id: "11"
              cudnn_id: "8"
              cuda_pin: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin"
              cuda_deb: "https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2004-11-8-local_11.8.0-520.61.05-1_arm64.deb"
              cuda_toolkit: "cuda"
              cudnn_deb: "https://mirrors.uwucocoa.moe/cuda/cudnn-local-repo-ubuntu2004-8.9.7.29_1.0-1_arm64.deb"
              cudnn_package: "libcudnn8-dev"
          - pair:
              arch: aarch64-linux-gnu
              runner: ubicloud-standard-4-arm
              cuda_id: "11"
              cudnn_id: "9"
              cuda_pin: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin"
              cuda_deb: "https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2004-11-8-local_11.8.0-520.61.05-1_arm64.deb"
              cuda_toolkit: "cuda"
              cudnn_deb: "https://developer.download.nvidia.com/compute/cudnn/9.10.2/local_installers/cudnn-local-repo-ubuntu2004-9.10.2_1.0-1_arm64.deb"
              cudnn_package: "cudnn-cuda-12"
          - pair:
              arch: aarch64-linux-gnu
              runner: ubicloud-standard-4-arm
              cuda_id: "12"
              cudnn_id: "8"
              cuda_pin: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin"
              cuda_deb: "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda-repo-ubuntu2004-12-9-local_12.9.1-575.57.08-1_arm64.deb"
              cuda_toolkit: "cuda-toolkit-12-5"
              cudnn_deb: "https://mirrors.uwucocoa.moe/cuda/cudnn-local-repo-ubuntu2004-8.9.7.29_1.0-1_arm64.deb"
              cudnn_package: "libcudnn8-dev"
          - pair:
              arch: aarch64-linux-gnu
              runner: ubicloud-standard-4-arm
              cuda_id: "12"
              cudnn_id: "9"
              cuda_pin: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin"
              cuda_deb: "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda-repo-ubuntu2004-12-9-local_12.9.1-575.57.08-1_arm64.deb"
              cuda_toolkit: "cuda-toolkit-12-5"
              cudnn_deb: "https://developer.download.nvidia.com/compute/cudnn/9.10.2/local_installers/cudnn-local-repo-ubuntu2004-9.10.2_1.0-1_arm64.deb"
              cudnn_package: "cudnn-cuda-12"

    name: aarch64-linux-gnu-cuda${{ matrix.pair.cuda_id }}-cudnn${{ matrix.pair.cudnn_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mix compile (with contrib modules)
        run: |
          ls -la
          cp -a .github/scripts/*.sh ./
          chmod +x *.sh
          ./script-to-build-gnu.sh "${{ matrix.pair.cuda_pin }}" "${{ matrix.pair.cuda_deb }}" "${{ matrix.pair.cuda_toolkit }}" "${{ matrix.pair.cuda_id }}" "${{ matrix.pair.cudnn_deb }}" "${{ matrix.pair.cudnn_package }}" "${{ matrix.pair.cudnn_id }}" "${{ env.OTP_VERSION }}" "${{ env.ELIXIR_VERSION }}" "${{ env.TRIPLET }}" "${GITHUB_REF}"

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.tar.gz
            artifacts/*.sha256
